---
- name: Download and install apache-tomcat
  hosts: all
  sudo: true
  tasks:
     - name: Download apache-tomcat
       unarchive:
         src: https://www-eu.apache.org/dist/tomcat/tomcat-9/v9.0.14/bin/apache-tomcat-9.0.14.zip
         dest: /opt
         remote_src: yes
